"""
Builder Agent
- Picks the top scored idea from ideas.json
- Marks it as 'built'
- Script is generated by Claude and saved to scripts/
"""

import json
from datetime import datetime

def get_top_idea(ideas_path="ideas/ideas.json"):
    with open(ideas_path, "r") as f:
        data = json.load(f)

    pending = [i for i in data["ideas"] if i["status"] == "pending"]
    if not pending:
        print("No pending ideas!")
        return None

    pending.sort(key=lambda x: x["score"], reverse=True)
    return pending[0]

def mark_built(idea_id, script_path, ideas_path="ideas/ideas.json"):
    with open(ideas_path, "r") as f:
        data = json.load(f)

    for idea in data["ideas"]:
        if idea["id"] == idea_id:
            idea["status"] = "built"
            idea["built_at"] = datetime.now().isoformat()
            idea["script_path"] = script_path
            break

    with open(ideas_path, "w") as f:
        json.dump(data, f, indent=2)

    print(f"Marked idea {idea_id} as built -> {script_path}")

if __name__ == "__main__":
    top = get_top_idea()
    if top:
        print(f"\nTop idea to build today:")
        print(f"  Title: {top['title']}")
        print(f"  Score: {top['score']}")
        print(f"  Description: {top['description']}")
